### ISSUE TITLE
Protocol gateway nugets out of sync

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-iot-protocol-gateway#101]
![image](https://user-images.githubusercontent.com/969938/28469779-007ccb36-6dfd-11e7-9d14-26d770b9527a.png)

**Comment by nayato** [comment]
we're not keeping versions in sync. we upgrade whenever there's reason to do so independently.

**Comment by onionhammer** [comment]
@nayato There is a reason. They have different dependencies.

CloudStorage 1.1.0 relies on DotNetty's deprecated "-signed" packages, whereas the other two ProtocolGateway libraries have moved on and upgraded to non-signed DotNetty libraries; The latest versions of Core and IoTHubClient aren't compatible with CloudStorage.

**Comment by nayato** [comment]
ok, that's an oversight. We'll release a new version today-tomorrow alongside a fix for failure to keep listening socket in a running state (see https://github.com/Azure/DotNetty/issues/271 for details)

**Comment by onionhammer** [comment]
@nayato any update on this?

**Comment by onionhammer** [comment]
Bump. Any update on this?

**Comment by onionhammer** [comment]
@nayato  Bump - still no release on this one

**Comment by mhertis** [comment]
We have the same problem with out of sync nuget packages, Is there anything we can do to speed this up?

**Comment by nayato** [comment]
@onionhammer @mhertis please try https://www.nuget.org/packages/Microsoft.Azure.Devices.ProtocolGateway.Providers.CloudStorage/1.2.0
