### ISSUE TITLE
Device disconnections during concurrent connect request

### ISSUE THREAD

**Issue by pragmaticqa** [Azure/azure-iot-protocol-gateway#104]
We are observing some issues in Protocol Gateway, when we try to connect a higher number of devices with higher concurrency. The issue we are observing is that we receive a connect packet just once for a particular device, but the point where PG creates a device scoped connection in IoT hub Client, the connection request is made more than once with same device scoped connection string. Due to this, we are seeing session eviction in the IoTHub (same device trying connect more than once to Iot hub). This results in  closing the connection between the device and PG as well.
 
We could conclude on this behavior by introducing a few logs statements in the code:
1.	In the Receive() method of IotHubClient, we have a log statement in the condition where the message is null.
2.	In the CreateFromConnectionStringAsync() of IotHubClient, we are printing the connection string, using which a device client was being created.
 
The connection string mentioned above ideally has to be unique for each device. But, when we enabled logging and tried to connect the devices, we were seeing that the connection string carries the deviceid of a different device instead of the current device for which the request has been created. This happens in cases where two devices have sent the connection request at the same time. 
 
Below are the test numbers:
----------------------------------------
Number of batches: 10
Number of devices per batch: 300
We try to activate the TCP channel for these 300 devices in a loop and wait until this batch is completed. Once a batch is completed, we start the next batch.
 
Below is a sample of the log statements we have observed :
-----------------------------------------------------------------------------------------------
DeviceI=**K2274100**. **ConnectionString=HostName=xxxx.azure-devices.net;DeviceId=K1529890**;SharedAccessKey===;X509Cert=False

**DeviceI=K1741670**. **ConnectionString=HostName=xxxx.azure-devices.net;DeviceId=K2795030**;SharedAccessKey=sxxx==;X509Cert=False

**Comment by nayato** [comment]
We've identified the cause for this. Here: https://github.com/Azure/azure-iot-protocol-gateway/blob/master/src/ProtocolGateway.IotHubClient/IotHubClient.cs#L78
`csb` is shared while it should not have been. Fix is coming in the next version. Likely, beginning of next week.

**Comment by pragmaticqa** [comment]
thank you for the update, this helps us. We suspected the same today and was about to add some mutex surrounding these statements. Will wait for a fix now, interested to know how this is being fixed.

**Comment by pragmaticqa** [comment]
Thank you for the update. Will wait for the fix

**Comment by pragmaticqa** [comment]
when could we expect the fix to make it into master ?
