### ISSUE TITLE
"Microsoft Azure IoT Protocol Gateway" documentation - broken link

### ISSUE THREAD

**Issue by stefanogiacco** [Azure/azure-iot-protocol-gateway#11]
Hello,
The page https://github.com/Azure/azure-iot-protocol-gateway/blob/master/README.md contains following broken link in "Diagnostics and Monitoring/Logging" paragraph: https://msdn.microsoft.com/en-us/library/azure/dn186185.aspx

Regards,
Stefano

**Comment by simonrolfe** [comment]
This seems to be fixed now.
