### ISSUE TITLE
Microsoft.Azure.IoT.Gateway/ message content type

### ISSUE THREAD

**Issue by almusawi** [Azure/azure-iot-protocol-gateway#114]
Hi,

I am using Iot hub edge (V1) and it works fine in sending the data. but by using Microsoft.Azure.IoT.Gateway ,the message class, I can not set the content type for the message before sending it to the Iothub. and I can not use the Microsoft.Azure.Devices.Client in the Iot edge model which has in the message class the message.ContentEncoding = "utf-32" and message.ContentType = "application/json";.

Could you please help in that?  How to add the content type to a message send by IoT edge model to Iot hub?

Thanks

**Comment by damonbarry** [comment]
I've copied this issue to the iot-edge repo, so you can close this one.

**Comment by nayato** [comment]
closing in favor of https://github.com/Azure/iot-edge/issues/505
