### ISSUE TITLE
Deploying Cloud Sample - References not correct

### ISSUE THREAD

**Issue by bastisk** [Azure/azure-iot-protocol-gateway#12]
I've been trying to package the cloud example in order to deploy the Gateway as a WorkerRole.

Some of the references could not be resolved. I used "Manage Nuget Packages for Solution" and restored missing packages, this fixed some errors but not all.

In Solution Explorer the following references are still marked with a warning sign:
- Microsoft.Azure.Devices.ProtocolGateway.Core
- Microsoft.Azure.Devices.ProtocolGateway.Providers.CloudStorage

Is there a way to resolve this or is this in fact an issue?

*Additional Information*
Complete Error Output from packaging:
https://gist.github.com/bastisk/342a0fed8ece3e4b79d9

*Environment*
- Visual Studio 2015 CE on Windows Server 2012 VM on Azure
- installed Azure SDK v2.7

**Comment by nayato** [comment]
@bastisk, thanks for reporting this! Looks like we've messed up nuget package references during the update. Should be fine now with #13 in.

**Comment by bastisk** [comment]
Agreed, works fine now. Thank you :)
