### ISSUE TITLE
Cannot find the certificate and private key to use for decryption.

### ISSUE THREAD

**Issue by spartyspartan** [Azure/azure-iot-protocol-gateway#19]
When deploying to Azure, Cloud services get to busy state and then restart - over and over again.

More detailed error msg in the table log is...
"There is no appropriate cert in the store LOCAL_MACHINE\MY to decrypt the data, the data must be decrypted with the cert with serial number 4c51f6477467c09a41200bb1822d4700 and issued by 'DC=Windows Azure Service Management for Extensions'. Please make sure this cert is installed to the store LOCAL_MACHINE\MY along with the corresponding private key."

This seems to be the "default" key added to cloud services environment based on the issuer.

**Comment by nayato** [comment]
are you deploying using the instructions here:
https://github.com/Azure/azure-iot-protocol-gateway/#deploying-cloud-sample ?

**Comment by krishnabatham** [comment]
I am facing same issue. I have follow instruction as mention here https://github.com/Azure/azure-iot-protocol-gateway/#deploying-cloud-sample .

Any guidance will be helpful

Thanks

**Comment by myheren** [comment]
facing the same issue, too, could some one help?

**Comment by yshahin** [comment]
any updates on this?

**Comment by danielwcr** [comment]
Could someone post the solution for this here?
