### ISSUE TITLE
Azure deployment not uploading

### ISSUE THREAD

**Issue by egadgetjnr** [Azure/azure-iot-protocol-gateway#22]
Hi,
I'm having issues with trying to deploy the gateway to Azure using the instructions provided to the letter.

I have sucessfully got the power-shell script to run (without any errors) and it appears to be fine. However, when I go to the Azure Portal and look at the newly created Cloud Service, there is nothing running or even uploaded in both Staging or Production. 

Would you be able to hopefully help me out with some advice as to what I may be doing wrong, or what you'd like me to send through to help?

Thanks in advance.

**Comment by nayato** [comment]
@egadgetjnr closing this as we don't see any issues ourselves at this point. Feel free to re-open if it's still the case for you. Also, we'll make sure to respond promptly this time around.
