### ISSUE TITLE
In Cloud to device scenario , Message having issues with topic name shuts down the channel

### ISSUE THREAD

**Issue by whizlingo** [Azure/azure-iot-protocol-gateway#23]
In case of Cloud of device scenario if there is an issue with the Topic routing and an exception occurs (Invalid operation exception when an error occurs in template.Bind(context) call) , the message does not get rejected instead the  Server closes the channel but does not remove the message from the IOT hub which would  mean if the client reconnects , the protocol gateway will try to deliver again and again close the channel. is this an expected behavior ?

**Comment by nayato** [comment]
fixed by #32
