### ISSUE TITLE
QoS 2 table persistence provider: stored entries are not scoped by device ID

### ISSUE THREAD

**Issue by whizlingo** [Azure/azure-iot-protocol-gateway#28]
Below is the mechanism used by the Protocol Gateway for generating the Packet ID in the Cloud-to-Device scenario
            int packetId = unchecked((ushort) {SequenceNumberOfMessage});
            int generatedPacketID = packetId |= 0x8000; // set 15th bit
The current Packet id generation logic uses Sequence number property of IoT Hub message which is a number assigned by IoT Hub to each cloud to device message and is unique per device queue. Along with that it uses bitwise operators to differentiate in the packet id generation at different QoS levels. Since the packet identifier is used as the row key for the QoS 2 persistence storage along with hash of it as the partition key, it will ensure uniqueness for packets from a device but not across multiple devices.

Would it make sense to change the logic of Packet Id generation to include Client Id in it for all the cloud to device messages ?. In the same way in order to avoid conflicts between packet id generated for Cloud to device messages and Device-to-Cloud messages, we can use the combination of Device Id and packet Identifier(Since in our case Client id and Device id are different ) while persisting the state of Device-to-Cloud  messages. Please suggest.

**Comment by nayato** [comment]
fixed by #32
