### ISSUE TITLE
MQTT topics

### ISSUE THREAD

**Issue by snobu** [Azure/azure-iot-protocol-gateway#31]
![image](https://cloud.githubusercontent.com/assets/6472374/13234735/d6e10140-d9c2-11e5-8fd9-2921a3e572af.png)

Using Paho or MQTT.fx i can't send a message (device->cloud) to `devices/{deviceId}/messages/events` as per document here https://github.com/Azure/azure-iot-protocol-gateway/blob/master/docs/DeveloperGuide.md#subscriptions-and-topic-names

Result is: __$PG.Unmatched__

>If the topic name of a message doesn’t match the corresponding template, two special properties will be added to the message: ‘Unmatched’ set to ‘True’ and 'Subject' set to the topic name from the MQTT message.

Please clarify structure and topic.

NOTE: I'm not sending to protocol gateway but talking native MQTT to IoT Hub endpoint.

**Comment by nayato** [comment]
@snobu, can you try adding "/" to topic name? If that works then it is an issue we'll address very soon.

**Comment by snobu** [comment]
No go. 
```
'$PG.Unmatched': 'True'
'$PG.Subject': '/devices/Mega/messages/events'
```

This works, which makes me wonder what topic is the C# SDK publishing to. Not trivial to sniff the MQTT packets since i'm not aware of a way to keep it from doing TLS (is there?):
```csharp
  // talk MQTT to IoT Hub
deviceClient = DeviceClient.Create(iotHubUri,
new DeviceAuthenticationWithRegistrySymmetricKey(deviceName, deviceKey), TransportType.Mqtt);

...

var messageString = JsonConvert.SerializeObject(telemetryDataPoint);
                var message = new Message(Encoding.ASCII.GetBytes(messageString));
                await deviceClient.SendEventAsync(message);
```

**Comment by nayato** [comment]
did you add the slash and it's still without the slash in EventHub? ok.. can you try `devices/Mega/messages/events/a=b`?

**Comment by snobu** [comment]
That works. It also works just by having a trailing slash.
![image](https://cloud.githubusercontent.com/assets/6472374/13251212/7f05cf58-da37-11e5-9235-97acfad6ec15.png)

Thanks!

**Comment by nayato** [comment]
There is no actual reason not to support topic without a slash at the end and it will be fixed.

**Comment by winne42** [comment]
still not fixed as of today... :-(

**Comment by jtmoderate876** [comment]
Anyone have any idea why I can't get data using mqtt.fx connecting to mysolution}.azure-devices.net?

I can successfully subscribe using Client ID HP9470mMQTTFX - I get the green light connected.

I can then subscribe to all of these:
devices/HP9470mMQTTFX/messages/events/#
devices/1CB19D/messages/events/#
devices/HP9470mMQTTFX/messages/devicebound/#
devices/1CB19D/messages/devicebound/#

My real device 1CB19D shows updates in Device Explorer (gui tool) and iothub-explorer (command line tool)

But my MQTT.fx client never sees anything, including 1CB19D and anything I try from publish such as publishing to:
Topic: devices/HP9470mMQTTFX/messages/events/
Value: Hello

I have some experience with other MQTT brokers and haven't had this problem but clearly Azure MQTT is different.

**Comment by robichaud** [comment]
@jtmoderate876 The Protocol Gateway is not a MQTT Broker. It provides protocol translation for the IoT Hub. A good place to start learning about this is here [https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-what-is-iot-hub](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-what-is-iot-hub) .

**Comment by harshavardhankadiri** [comment]
@jtmoderate876, did you find  way to subscribe the messages in MQTT.fx when you publish?

**Comment by jtmoderate876** [comment]
No, you can’t, it is not a real MQTT broker.

 @rabichaud is exactly right.
