### ISSUE TITLE
QoS 2 Support: Multiple rows are returned if there are more than one message in QoS 2 table storage

### ISSUE THREAD

**Issue by sachin85** [Azure/azure-iot-protocol-gateway#35]
In the current Implementation, Table storage query formed, returns all the rows present in the table storage rather than returning only row with matching partition key and row key.

Instead if query is constructed as below, this works fine.
TableQuery<TableMessageDeliveryState> query = new TableQuery<TableMessageDeliveryState>().Where(filter);

**Comment by nayato** [comment]
fixed by #38
