### ISSUE TITLE
Getting issue while deploye Azure protocol gateway to cloud as worker role

### ISSUE THREAD

**Issue by krishnabatham** [Azure/azure-iot-protocol-gateway#40]
I am trying to configure IOT protocol gateway (MQTT protocol) on azure as a worker role. I have follow all the step mention by [Microsoft Deploying Cloud Sample](https://github.com/Azure/azure-iot-protocol-gateway) .But I am doing same deployment process using power shell.But deployment process failed at last stage.Please check image for more details on power shell command.
![error](https://cloud.githubusercontent.com/assets/1967797/14280278/80e586ea-fb4f-11e5-890f-def6bb377e9c.png)

Thanks in advance.

**Comment by nayato** [comment]
sorry for the delay on this. You should have put connection string in quotes to make sure it is passed as a single parameter to the script.
