### ISSUE TITLE
Protocol gateway does not follow Mqtt Spec if TTL is sent as "zero" by client 

### ISSUE THREAD

**Issue by sachin85** [Azure/azure-iot-protocol-gateway#46]
Setting the Keep alive time out to Max keep alive time out in case the client sends it as zero in MQTT packet is not aligned with MQTT Specification.

**Comment by nayato** [comment]
@sachin85, can you please confirm that `MaxKeepAliveTimeout` setting is set to "-" (or any other non-timespan value) or not set at all? See description for configuration settings here: https://github.com/Azure/azure-iot-protocol-gateway#configuration-settings.

**Comment by nayato** [comment]
@sachin85, any news on this?

**Comment by sachin85** [comment]
we want to have default value set to for keep alive if client sends a value above upper limit. But if device is sending zero, which is wthin the upperlimit set by us, it should behave as per Mqtt Spec, which is it should always remain conencted.

**Comment by nayato** [comment]
MQTT spec leaves it up to server impl to decide when to disconnect clients:
> Note that a Server is permitted to disconnect a Client that it determines to be inactive or non-responsive at any time, regardless of the Keep Alive value provided by that Client.
If you are OK allowing clients to be connected eternally (Keep Alive=0) then there's no real value enforcing upper limit on non-zero Keep Alive value. Then you may configure `MaxKeepAliveTimeout` not to be enforced as shown above.

**Comment by sachin85** [comment]
That make sense.
Marking it closed.
