### ISSUE TITLE
No longer compatible with new Microsoft.Azure.Devices.Client releases

### ISSUE THREAD

**Issue by robichaud** [Azure/azure-iot-protocol-gateway#51]
`ReadOnlyByteBufferStream` throws a `NotSupportedException` when `Position` is called:
[https://github.com/Azure/azure-iot-protocol-gateway/blob/master/src/ProtocolGateway.Core/ReadOnlyByteBufferStream.cs#L44](url)

`RetryDelegatingHandler` calls the stream's `Position` when sending messages `SendMessageWithRetryAsync`:
[https://github.com/Azure/azure-iot-sdks/blob/master/csharp/device/Microsoft.Azure.Devices.Client/Transport/RetryDelegatingHandler.cs#L178](url)

**Comment by mtuchkov** [comment]
Thank you for report. According to the MSDN this is expected behavior to throw NotSupportedException if stream is not seekable even for Postition.get, so it is addressed in the upcoming release of Device Client SDK.

**Comment by mtuchkov** [comment]
[Fix retry for non-seekable stream](https://github.com/Azure/azure-iot-sdks/commit/296618527dcb698c9ff1399d373d2f85dbd65afd)
